version: "3.9"
services:
  rails:
    build: .
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      VITE_RUBY_HOST: vite
    volumes:
      - .:/app
    depends_on:
      - vite
  vite:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    environment:
      DEBUG: '*vite*'
      RAILS_ENV: development
      VITE_RUBY_HOST: 0.0.0.0
    command: ./bin/vite dev
    ports:
      - "3036:3036"
    volumes:
      - .:/app
