version: "3.9"
services:
  rails:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    entrypoint: "bin/rails server --binding=0.0.0.0"
    depends_on:
      - vite
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    environment:
      VITE_RUBY_HOST: vite
    volumes:
      - ./app:/app/app
      - ./bin:/app/bin
      - ./config:/app/config
      - ./db/:/app/db
      - ./lib:/app/lib
      - ./public:/app/public
      - ./config.ru:/app/config.ru
      - ./Gemfile:/app/Gemfile
      - ./Gemfile.lock:/app/Gemfile.lock
      - ./Rakefile:/app/Rakefile
  vite:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    entrypoint: "bin/vite dev"
    tty: true
    stdin_open: true
    ports:
      - "3036:3036"
    volumes:
      - ./app:/app/app
      - ./bin:/app/bin
      - ./config:/app/config
      - ./db/:/app/db
      - ./lib:/app/lib
      - ./public:/app/public
      - ./config.ru:/app/config.ru
      - ./Gemfile:/app/Gemfile
      - ./Gemfile.lock:/app/Gemfile.lock
      - ./Rakefile:/app/Rakefile
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./vite.config.ts:/app/vite.config.ts